name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main, master]

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni

      - name: Install and build CodingBases01
        run: |
          cd codingbases01
          nci
          nr build slides.md --base /${{ github.event.repository.name }}/codingbases01/ --out ../dist/codingbases01

      - name: Install and build OOP01
        run: |
          cd oop01
          nci
          nr build slides.md --base /${{ github.event.repository.name }}/oop01/ --out ../dist/oop01

      - name: Install and build UEWORLDCTRL01
        run: |
          cd ueworldctrl01
          nci
          nr build slides.md --base /${{ github.event.repository.name }}/ueworldctrl01/ --out ../dist/ueworldctrl01

      - name: Copy root files
        run: |
          cp index.html dist/index.html
          cp .nojekyll dist/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
